version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: PROD
      PORT: 3000
      DB_CONNECTION: postgres://postgres:pass@db:5432/backendsystem
      JWT_SECRET_KEY: accessTokenPrivateKey
      DB_HOST: db
    depends_on:
      - db
       
  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: backendsystem